### ISSUE TITLE
Is this actually necessary?

### ISSUE THREAD

**Issue by willl** [vscode-langservers/extractor#1]
Hi,

Saw this posted to reddit recently and was wondering why you weren't just using the [exposed language servers](https://github.com/Microsoft?utf8=%E2%9C%93&q=languageservice&type=&language=) under the Microsoft org rather than needing to extract it out of the VS Code tree?

CSS - https://github.com/Microsoft/vscode-css-languageservice
JSON - https://github.com/Microsoft/vscode-json-languageservice
HTML - https://github.com/Microsoft/vscode-html-languageservice

I'm asking out of genuine curiosity. I do not work for Microsoft etc.

**Comment by DeltaEvo** [comment]
Hello @willl,

These `languageservice` are currently libraries to write language server, it's the core of it.
But it's unusable because you need to write some code to use this like "classical" language servers
What I extract from the tree are these little wrappers that use a `languageservice` under the hood 
For example https://github.com/vscode-langservers/vscode-json-languageserver/blob/master/src/jsonServerMain.ts#L21
